# Site settings
#destination: public
url: "https://ifromz.info"
baseurl: ""
title: "Fromz Prajuktar"
description: "Fromz Prajuktar, Personal website and Profile."
keywords: "fromz, prajuktar, kaewmanee, developer, researcher, blog"
favicon: "/img/favicon.png"
black-favicon: "/img/favicon.png"
google-tracking-id: "UA-71824673-1"
disqus-shortname: "pkfrom"

force-https: True

email: "pkfromz@gmail.com"
author: "iFromz"
# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
#  Blog: 'blog'
  Timeline: 'timeline'
  Portfolio: 'portfolio'
  Contact: 'contact'

# About variables
dynamic-typing: true
shuffle: false # Shuffle the lines.
loop: True
loop-count: false # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hi. Welcome!! "
  - text: "I'm Software Developer, (designer sometimes.)"
  - text: "Keep at it. Never give up !"
  - text: "I'll either find a way or make one myself."

me-img: "/img/fromz1x1.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 128

paginate: 15

email-share: False
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

paginate_path: "blog/page:num"

# Career variables

events:
#  - image: "/img/career/gsoc_2015.jpg"
#    date: "March 2015 - August 2015"
#    description: "description"
  - image: "/img/career/issoftware.jpg"
    date: "Sep 2013 - 2015"
    description: "Software Development @ <a href=\"http://todayissoftware.com\" target=\"_blank\">IS Software Co., Ltd.</a><br>Development CMMS System (PHP, MySQL, SQL Server)"
  - image: "/img/career/cornerme.jpg"
    date: "2012 - 2013"
    description: "Programmer @ <a href=\"http://cornerme.net\" target=\"_blank\">Cornerme Co., Ltd.</a><br>Interactive development on software <a href=\"http://www.ventuz.com\" target=\"_blank\">Ventuz Designer</a> (.NET)"
  - image: "/img/career/eng.jpg"
    date: "2009 - 2013"
    description: "Bachelor of Engineering @ (<a href=\"http://engineer.utcc.ac.th\" target=\"_blank\">Computer Engineering</a>) in The University of the Thai Chamber of Commerce (<a href=\"http://www.utcc.ac.th\" target=\"_blank\">UTCC</a>) "
  - image: "/img/career/controller.jpg"
    date: "2006 - 2009"
    description: "Certificate of Vocational Education @ Electronics in <a href=\"http://bits.ac.th\" target=\"_blank\">Bangkok College Of Industrial Technology</a> "


awards:
  - title: "<a href=\"http://engineer.utcc.ac.th/upload/News/Attachment/E6RT26235QEISCMDOCUO07A1MIKJZ8MYMYY51E.pdf\" target=\"_blank\">รางวัลชนะเลิศ</a><br> โครงการประกวดสิ่งประดิษฐ์และนวัตกรรม คณะวิศวกรรมศาสตร์"
    date: "ประจำปี พ.ศ.2555"
  - title: "Create the <a href=\"//cdn.ifromz.info/profile/Interactive_Touch_Marker.pdf\" target=\"_blank\">Interactive Touch Table</a><br>  product for <a href=\"//www.wjtechnology.net\" target=\"_blank\">WJ Technology</a>"
    date: ""
  - title: "ระบบบันทึกการประชุม Drug Committee and Regulation Online"
    date: "<a href=\"http://www.fda.moph.go.th/\" target=\"_blank\">สํานักงานคณะกรรมการอาหารและยา</a>"
  - title: "website มูลนิธิปวีณาหงสกุลเพื่อเด็กและสตรี <br><a href=\"http://www.pavenafoundation.or.th\" target=\"_blank\">www.pavenafoundation.or.th</a>"
    date: ""
#  - title: "website iinbrand.com <br><a href=\"http://iinbrand.com\" target=\"_blank\">iinbrand.com</a>"
#    date: ""


# First image of the Career timeline
career-img: "/img/career/computer.png"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
#  - title: "facebook"
#    url: "https://facebook.com/pkfrom"
  - title: "twitter"
    url: "https://twitter.com/pkfrom"
  - title: "github"
    url: "https://github.com/pkfrom"
  - title: "linkedin"
    url: "https://linkedin.com/in/pkfrom"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1ERGU2bUPc8vr8nXmTpzbC3sWfPdnQXE4F"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "CNAME","LICENSE", "README.md", 'info.mk', "scripts", "public", "unesp", "Gemfile*"]

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
