# Site settings
#destination: public
url: "https://ifromz.info"
baseurl: ""
title: "Fromz Prajuktar"
description: "Fromz Prajuktar, Personal website and Profile."
keywords: "fromz, prajuktar, kaewmanee, developer, researcher, blog"
favicon: "/img/favicon.png"
black-favicon: "/img/favicon.png"
google-tracking-id: "UA-71824673-1"
disqus-shortname: "pkfrom"

#force-https: False

email: "pkfromz@gmail.com"
author: iFromz.
# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
#  Blog: 'blog'
  Timeline: 'timeline'
  Awards: 'awards'
  Contact: 'contact'

# About variables
dynamic-typing: true
shuffle: false # Shuffle the lines.
loop: True
loop-count: false # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hi. Welcome!! "
  - text: "I'm Software Developer, and designer some time."

me-img: "/img/fromz1x1.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 128

paginate: 15

email-share: False
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

paginate_path: "blog/page:num"

# Career variables

events:
#  - image: "/img/career/gsoc_2015.jpg"
#    date: "March 2015 - August 2015"
#    description: "description"
#  - image: "/img/career/unesp.jpg"
#    date: "April 2015 - Until now"
#    description: "description"
  - image: "/img/career/triata.jpg"
    date: "September 2013 - January 2015"
    description: "description"
  - image: "/img/career/issoftware.jpg"
    date: "February 2012 - December 2014"
    description: "description"
  - image: "/img/career/cornerme.jpg"
    date: "2010 or 2011"
    description: "description"


awards:
  - title: "title"
    date: "2014"
#  - title: "title"
#    date: "2014"

# First image of the Career timeline
career-img: "/img/career/computer.png"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
#  - title: "facebook"
#    url: "https://facebook.com/pkfrom"
  - title: "twitter"
    url: "https://twitter.com/pkfrom"
  - title: "github"
    url: "https://github.com/pkfrom"
  - title: "linkedin"
    url: "https://linkedin.com/in/pkfrom"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "CNAME","LICENSE", "README.md", 'info.mk', "scripts", "public", "unesp", "Gemfile*"]

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
